### ISSUE TITLE
empty, dirty fields don't match

### ISSUE THREAD

**Issue by rienheuver** [TheSharpieOne/angular-input-match#10]
Example fields:
`<input ng-model="user.password" type="password">`
`<input ng-model="user.checkpassword" type="password" match="user.password">`
If I enter data in user.checkpassword and then remove it again (making it an invalid match for a small time), it will remain unmatched. The fields do not match any longer even though they are both empty.

**Comment by TheSharpieOne** [comment]
In this case, it looks like you may have some other validation on the first field.  When that validation fails, it set the value to `undefined`, when the confirmation field is empty it is `""` (empty string), they do not match with `===`.

This looks to relate to #5

**Comment by rienheuver** [comment]
The first field does not have any validation. However, it is a password field so maybe that has something to do with it. This directive will mostly be used on password fields though so a fix is wanted.

**Comment by TheSharpieOne** [comment]
I see, you never touched the first field, by default it is `undefined`.  After touching the second field and removing the values, it became `""`.  I'll look into getting the `$viewValue` for the field that the match directive is *not* on when I get time.

**Comment by rienheuver** [comment]
Sounds good to me, hope it will work out.

**Comment by TheSharpieOne** [comment]
A new ability was added, see the README section about "Validate Against the `$viewValue` shown in the input"
