### ISSUE TITLE
Wrong result when the input type is "email"

### ISSUE THREAD

**Issue by benjaminsuch** [TheSharpieOne/angular-input-match#13]
Hi,

when you compare two input fields of type "email", the validator returns false when both values are the same. You have to enter a valid email adress to get the correct result. 

I made a quick plunk here: http://plnkr.co/edit/gS7ytb

It's not a big thing, since you want to have valid email adresses but it's still dirty to let this bug open.

Edit:
This error occurs also on other input types, when the input control in `data-match` has other failed validations, such like "minlength" for example.

Edit²:
Sorry, duplicate of https://github.com/TheSharpieOne/angular-input-match/issues/5

**Comment by benjaminsuch** [comment]
A current solution is btw to add `ng-model-options="{allowInvalid: true}` to the compared input control

**Comment by TheSharpieOne** [comment]
This is related to #5. Since this seems to be coming up more and more, I'll have to actually start looking into a solution

**Comment by TheSharpieOne** [comment]
A new ability was added, see the README section about "Validate Against the `$viewValue` shown in the input"
