### ISSUE TITLE
Buggy behaviour when using built in input types like text, password.

### ISSUE THREAD

**Issue by darkshadow** [TheSharpieOne/angular-input-match#15]
Hi,

I am facing issue with $error.parse. Doesn't matter whether I pass model value or form value object (viewValue) to match. Sometimes I am left with {parse: true} in $errors. Even though all other validations have passed. And also element is classed with ng-invalid-parse.

I am using 1.3.9 can confirm same issue with 1.3.8 too.

Interestingly I don't get this issue when using angular provided type validators like email.

Thanks.

**Comment by TheSharpieOne** [comment]
There is a 1.3.x branch that works for 1.3.x.  Its needs a little cleanup and probably need to be moved to master (and a 1.2.x branch created from what is in mater now).

**Comment by darkshadow** [comment]
Thanks, For now I am switching to the 1.3 branch. For my current needs that's sufficient.

**Comment by TheSharpieOne** [comment]
1.3.x branch as been updated and moved to master and released for bower installations.
