### ISSUE TITLE
Not working for email type fields.

### ISSUE THREAD

**Issue by vikrambabu2** [TheSharpieOne/angular-input-match#19]
The directive is not working properly for email type input fields.

Please open this fiddler http://jsfiddle.net/352brrj2/
Steps to reproduce:
1.  Enter "xyz" email field.
2.  Enter "xyz" in confirm email field.
3.  Go back to email field and change value to "xyz@gmail.com"
4.  Continue changing the value entered in email field.

Output:
You can see that after step3, the validation message of confirm email field is getting cleared, which should not. Also you can see that, on entering characters in email field, the validation gets applied to compare field on and off.

**Comment by TheSharpieOne** [comment]
Please see the section of the [README.md](https://github.com/TheSharpieOne/angular-input-match/blob/master/README.md) about Validate Against the $viewValue shown in the input (its at the bottom of the README.me).  

What is happening is you are not entering a valid email, so the model is `undefined`.  Match is matching against `undefined`.  If you want to match what is displayed in the input field when the field is invalid, you need to match against the form field (`match="formName.fieldName"`) with the name of your form and field respectfully

The README.md goes into a little detail as to why this is necessary, but when you think about it, you can have 10 fields tied to the same model, and each of those fields can have different values when they are invalid.  This means you'll have to match an input and not a model.

Here is your example fixed: http://jsfiddle.net/TheSharpieOne/352brrj2/1/

**Comment by vikrambabu2** [comment]
I have tried the solution of validating against $viewValue . No, it is not working. Still issue is there. Open the fiddle you have given above. Try the same steps to reproduce

Steps to reproduce:
1. Enter "xyz" email field.
2. Enter "xyz" in confirm email field.
3. Go back to email field and change value to "xyz@gmail.com"
4. Continue changing the value entered in email field.

Now changing value in email field is actually clearing errors of confirm email field. And for every alternative character entered in email field, it is triggering validation of confirm email field.

**Comment by TheSharpieOne** [comment]
A fix has been merged, the example in my previous comment now works with the validation messing up on every other character.
