### ISSUE TITLE
Input match fails for case sensitive mails

### ISSUE THREAD

**Issue by vikrambabu2** [TheSharpieOne/angular-input-match#22]
In general, emails are case insensitive. So the directive is failing in this case. Actually this is not a bug. Can we enhance the directive behavior by allowing the user to set an attribute like case-sensitive-match = true or false.

**Comment by TheSharpieOne** [comment]
I'm horrible at typing and `insensitive` is not so easy to type... so I went with `caseless`
adding `match-caseless="true"` (true can be a scope var as well to make it toggle-able) will trigger the case insensitive matching.

```
<input ng-model="confirmation" match="original" match-caseless="true" />
```
