### ISSUE TITLE
match validation is incorrect if source field is invalid

### ISSUE THREAD

**Issue by amichair** [TheSharpieOne/angular-input-match#5]
Say you have a password field with some validator on it, such as requiring it to be at least 8 chars long. Then you have a password2 confirmation field which uses the match directive to make sure it matches the password field. If one enters the same value on both fields, but the value does not pass the password field's validation (e.g. only 2 chars are entered), then password2 is incorrectly marked as invalid even though it does match the password field.

The match directive should only mark the field as invalid if its value is not identical to the source field's value, regardless of whether the source field has other validation issues. The current behavior causes incorrect error messages to be displayed to the user, e.g. a "passwords do not match" error is shown in addition to an 'invalid password length' error, whereas only the latter is true, and once the user fixes it, only then should the second message be shown.

**Comment by TheSharpieOne** [comment]
A new ability was added, see the README section about "Validate Against the `$viewValue` shown in the input"
